seq = input("Введите последовательность ДНК: ")
seq_upper = seq.upper()
a_count = seq_upper.count('A')
t_count = seq_upper.count('T')
g_count = seq_upper.count('G')
c_count = seq_upper.count('C')
length = len(seq_upper)
print("\n=== Анализ последовательности ДНК ===\n")
print(f"Последовательность в верхнем регистре: {seq_upper}\n")
print("Подсчёт нуклеотидов:")
print(f"A: {a_count}")
print(f"T: {t_count}")
print(f"G: {g_count}")
print(f"C: {c_count}\n")
print(f"Общая длина: {length} нуклеотидфов")